<a href="https://colab.research.google.com/github/yt20031219/PytorchDataManipulation/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import the PyTorch library

In [ ]:
import torch

arange(n) creates a vector of evenly spaced values, starting at 0 (included) and ending at n (not included)<br>
  -- dtype=torch.X: https://pytorch.org/docs/stable/tensors.html

In [ ]:
x = torch.arange(20, dtype=torch.float64)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19.], dtype=torch.float64)

number of elements in a tensor 

In [ ]:
x.numel()

20

 transform vector x whose shape is (12,) to a matrix X with shape (4, 5)<br>
   -- equivalently called x.reshape(-1, 5) or x.reshape(4, -1).

In [10]:
X = x.reshape(4, 5)
X

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]], dtype=torch.float64)

tensor’s shape (the length along each axis)

In [11]:
X.shape

torch.Size([4, 5])

tensors initialized to contain all zeros<br>
  -- or ones by calling torch.ones((2, 3, 4))

In [12]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])